In [6]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 594 ms
Wall time: 595 ms


In [10]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 16 ms


In [12]:
data = np.random.randn(2, 3)

In [14]:
data

array([[-1.38068398, -1.1360558 ,  1.16905407],
       [ 0.04252151,  0.3187662 , -0.04013996]])

In [16]:
data * 10

array([[-13.80683984, -11.36055804,  11.69054074],
       [  0.42521508,   3.18766198,  -0.40139964]])

In [17]:
data + data

array([[-2.76136797, -2.27211161,  2.33810815],
       [ 0.08504302,  0.6375324 , -0.08027993]])

In [22]:
data.shape, data.dtype

((2, 3), dtype('float64'))

In [25]:
# python list
data1 = [6, 3.4, 2, 0, 1]
# np ndarray
arr1 = np.array(data1)
arr1

array([6. , 3.4, 2. , 0. , 1. ])

In [31]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
#      배열차원   배열 n*m
arr2, arr2.ndim, arr2.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 2,
 (2, 4))

In [32]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [42]:
# range 대응
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
l = [[1, 2], [3, 4]]
np.ones_like(l)

array([[1, 1],
       [1, 1]])

In [55]:
arr = np.array([1, 2, 3, 4, 5])
arr, arr.dtype

(array([1, 2, 3, 4, 5]), dtype('int32'))

In [59]:
arr.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [64]:
data = np.random.randn(2, 3)
data.astype(np.int32)  # 실수 => 정수는 소수점 모두 버림

array([[ 0, -1,  0],
       [ 0,  0,  0]])

In [71]:
str_arr = np.array(['1', '2.3', '5'])
str_arr.astype(np.float64)

array([1. , 2.3, 5. ])

In [76]:
float_arr = np.array([1.1])

str_arr.astype(float_arr.dtype)

array([1. , 2.3, 5. ])

In [77]:
# 산술연산

In [82]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [86]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [90]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [91]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])

In [94]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [95]:
# index/slicing

In [99]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr[5]

5

In [103]:
arr[5:8]

array([5, 6, 7])

In [106]:
arr[5:8] = 100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [108]:
arr_slice = arr[5:8]  # 슬라이스 복사본 X / 기존에서 필요한 부분만 다시 보여주기
arr_slice

array([100, 100, 100])

In [111]:
arr_slice[:] = 1000
arr_slice

array([1000, 1000, 1000])

In [113]:
arr  # 슬라이스는 복사가 아니다! Broadcating

array([   0,    1,    2,    3,    4, 1000, 1000, 1000,    8,    9])

In [122]:
# 슬라이스로 복사본을 만드려면,
copy_arr = arr[3:6].copy()

In [125]:
copy_arr[:] = 1
arr, copy_arr

(array([   0,    1,    2,    3,    4, 1000, 1000, 1000,    8,    9]),
 array([1, 1, 1]))

In [138]:
arr2d = np.random.randn(2, 3)
arr2d

array([[-1.23516034, -0.17758597,  1.47472801],
       [ 0.71654331,  0.80315212,  0.31597711]])

In [141]:
arr2d[0][1] == arr2d[0, 1]

True

In [145]:
arr2d[:, 1:2]

array([[-0.17758597],
       [ 0.80315212]])

In [146]:
# Bool

In [148]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [150]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [152]:
data = np.random.randn(7, 4)
data

array([[ 0.55401351,  0.42168354,  1.08407833,  1.58421567],
       [-0.826676  ,  0.13097413,  0.8193763 , -0.28476064],
       [ 0.92677994, -0.70337143,  0.04796952,  0.54932905],
       [ 1.35694505, -0.85607741, -0.21028428, -0.89539429],
       [-0.26270418,  0.05807059,  0.69091584,  1.64431603],
       [ 0.01360628, -1.32848624, -0.00556146, -1.70035477],
       [-0.97277689,  1.66893908,  1.12629996,  1.12057485]])

In [155]:
# data[[ True, False, False,  True, False, False, False]]
data[names == 'bob']  # row 수와 index 배열의 개수가 맞다면, True 인 애들만 남긴다.

array([[ 0.55401351,  0.42168354,  1.08407833,  1.58421567],
       [ 1.35694505, -0.85607741, -0.21028428, -0.89539429]])

In [162]:
cond = names == 'bob'
data[~cond]

array([[-0.826676  ,  0.13097413,  0.8193763 , -0.28476064],
       [ 0.92677994, -0.70337143,  0.04796952,  0.54932905],
       [-0.26270418,  0.05807059,  0.69091584,  1.64431603],
       [ 0.01360628, -1.32848624, -0.00556146, -1.70035477],
       [-0.97277689,  1.66893908,  1.12629996,  1.12057485]])

In [166]:
# data 중에서 음수들은 0으로 바꾼다.
data[data < 0] = 0

data

array([[0.55401351, 0.42168354, 1.08407833, 1.58421567],
       [0.        , 0.13097413, 0.8193763 , 0.        ],
       [0.92677994, 0.        , 0.04796952, 0.54932905],
       [1.35694505, 0.        , 0.        , 0.        ],
       [0.        , 0.05807059, 0.69091584, 1.64431603],
       [0.01360628, 0.        , 0.        , 0.        ],
       [0.        , 1.66893908, 1.12629996, 1.12057485]])

In [183]:
# Fancy Indexing
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [184]:
# index 를 list로 넘기기
arr[[4, 3, 0, 6]]  # 해당 index 순서대로 array를 재배치하여 제공

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [185]:
arr[[-1, -3, -5]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [189]:
# 배열 전치 (row/col 바꿈)
arr = np.arange(15).reshape(3, 5)

In [192]:
arr, arr.T

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]))

In [211]:
# 수학 메서드/통계 메서드
arr = np.random.randn(5, 4)
arr

array([[ 0.40487165,  0.01043839,  0.94045892,  0.30387913],
       [ 1.34442694,  0.56401619,  0.18437994,  0.26548946],
       [ 1.02452951,  0.9690232 , -2.38056517, -1.13852051],
       [ 0.87765686, -0.61558568,  0.84697825, -1.45943311],
       [-0.38248909,  0.77642476, -0.1203305 , -1.86439556]])

In [212]:
arr.mean()

0.027562678519197026

In [213]:
np.mean(arr)

0.027562678519197026

In [220]:
arr.sum()  # 전체 총합

0.5512535703839405

In [224]:
arr.sum(0)  # 각 열에 대해서 합계

array([ 3.26899587,  1.70431685, -0.52907856, -3.89298059])

In [227]:
arr.sum(1)  # 각 행에 대해 합계

array([ 1.65964809,  2.35831253, -1.52553297, -0.35038369, -1.59079039])