In [21]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [12]:
# Series => 1차원 배열
s = Series([4, 5, -7, 3])
s

0    4
1    5
2   -7
3    3
dtype: int64

In [96]:
s.values

array([ 4,  5, -7,  3], dtype=int64)

In [7]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
s = Series([4, 5, -7, 3], index=['d', 'b', 'a', 'c'])
s

d    4
b    5
a   -7
c    3
dtype: int64

In [15]:
s['d']

4

In [17]:
s[['c', 'a', 'b']]

c    3
a   -7
b    5
dtype: int64

In [19]:
s * 2

d     8
b    10
a   -14
c     6
dtype: int64

In [24]:
# s 는 Series 객체지만, np 함수들에도 사용할 수 있다.
np.exp(s)

d     54.598150
b    148.413159
a      0.000912
c     20.085537
dtype: float64

In [26]:
'd' in s, 'e' in s

(True, False)

In [29]:
d = {'서울': 123, '인천': 234, '부산': 30}
sd = Series(d)
sd

서울    123
인천    234
부산     30
dtype: int64

In [31]:
dosi = ['부산', '인천', '서울', '대전']
sd = Series(d, index=dosi)
sd

부산     30.0
인천    234.0
서울    123.0
대전      NaN
dtype: float64

In [33]:
sd.isnull()

부산    False
인천    False
서울    False
대전     True
dtype: bool

In [35]:
sd.name = '미세먼지'
sd.index.name = '도시'
sd

도시
부산     30.0
인천    234.0
서울    123.0
대전      NaN
Name: 미세먼지, dtype: float64

In [38]:
sd.index = ['가', '나', '다', '라']
sd.index.name = '글자'
sd

글자
가     30.0
나    234.0
다    123.0
라      NaN
Name: 미세먼지, dtype: float64

In [41]:
# DataFrame => 표/스프레드시트. 여러 컬럼 / 데이터 로우(레코드)
# Series 가 여러개 있는 Dict
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [43]:
frame.head()  # 선두 5개

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [44]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [47]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'dept'], index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop dept
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [49]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [51]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [57]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
dept      NaN
Name: three, dtype: object

In [68]:
frame2['dept'] = np.arange(6.)
frame2

year   state  pop  dept
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [80]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  dept  eastern
one    2000    Ohio  1.5   0.0     True
two    2001    Ohio  1.7   1.0     True
three  2002    Ohio  3.6   2.0     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False
six    2003  Nevada  3.2   5.0    False

In [81]:
del frame2['eastern']
frame2

year   state  pop  dept
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [83]:
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [85]:
# Transpose (전치행렬)
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [88]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [97]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [113]:
frame2.values

array([[2000, 'Ohio', 1.5, 0.0],
       [2001, 'Ohio', 1.7, 1.0],
       [2002, 'Ohio', 3.6, 2.0],
       [2001, 'Nevada', 2.4, 3.0],
       [2002, 'Nevada', 2.9, 4.0],
       [2003, 'Nevada', 3.2, 5.0]], dtype=object)

In [131]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [133]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [135]:
# Index 자료형은 바꾸기 불가능
obj.index[0] = 'd'

TypeError: Index does not support mutable operations

In [150]:
labels = pd.Index(np.arange(3))
obj2 = pd.Series([1.4, 2.3, 0], index=labels)
obj3 = pd.Series(['a', 'b', 'c'], index=labels)

labels is obj2.index, labels is obj3.index

(True, True)

In [163]:
frame3.index, frame3.columns

(Index([2001, 2002, 2000], dtype='int64', name='year'),
 Index(['Nevada', 'Ohio'], dtype='object', name='state'))

In [165]:
'Ohio' in frame3.columns

True

In [167]:
2003 in frame3.index

False

In [168]:
# Series / DataFrame 의 데이터 다루기

In [177]:
s1 = pd.Series([1.1, 2.2, 3.3, 4.4], index=['d', 'a', 'b', 'c'])
s1

d    1.1
a    2.2
b    3.3
c    4.4
dtype: float64

In [183]:
s2 = s1.reindex(['a', 'b', 'c', 'd', 'e'])
s2

a    2.2
b    3.3
c    4.4
d    1.1
e    NaN
dtype: float64

In [185]:
s1 is s2

False

In [186]:
# reindexing 중 데이터 보간/채워넣기

In [193]:
s3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
s3

0      blue
2    purple
4    yellow
dtype: object

In [194]:
# 빈 값들은 직전 값으로 채우기
s3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [204]:
f1 = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'Cal'])
f1

Ohio  Texas  Cal
a     0      1    2
c     3      4    5
d     6      7    8

In [210]:
f2 = f1.reindex(['a', 'b', 'c', 'd'])
f2

Ohio  Texas  Cal
a   0.0    1.0  2.0
b   NaN    NaN  NaN
c   3.0    4.0  5.0
d   6.0    7.0  8.0

In [317]:
f2.reindex(columns=['Texas', 'Utah', 'Cal'])

Texas  Utah  Cal
a    1.0   NaN  2.0
b    NaN   NaN  NaN
c    4.0   NaN  5.0
d    7.0   NaN  8.0

In [225]:
f2.loc[['a', 'b']]

Ohio  Texas  Cal
a   0.0    1.0  2.0
b   NaN    NaN  NaN

In [233]:
# Row / Col 삭제하기
s3 = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
s3

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [234]:
# drop 으로 'c' 색인을 지운 "새로운" Series 를 생성 가능
s4 = s3.drop('c')

In [238]:
s4

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [241]:
s3.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [248]:
f3 = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['a', 'b', 'c', 'd'])
f3

a   b   c   d
Ohio       0   1   2   3
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [249]:
# 별말 없으면, Row 삭제 => "새로운 DF" 반환
f3.drop(['New York', 'Utah'])

a  b  c  d
Ohio      0  1  2  3
Colorado  4  5  6  7

In [250]:
# Col 삭제하려면, axis=1 옵션을 준다.
f3.drop(['a', 'd'], axis=1)

b   c
Ohio       1   2
Colorado   5   6
Utah       9  10
New York  13  14

In [256]:
# 새로운 DF 반환 X / 기존 DF를 바꿔버림
f3.drop('Ohio', inplace=True)

In [258]:
f3

a   b   c   d
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [262]:
# 새로운 Series 반환 X / 기존 Series를 바꿔버림
s4.drop('a', inplace=True)

In [264]:
s4

b    1.0
d    3.0
e    4.0
dtype: float64

In [275]:
s1 = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
s1['b'], s1[1]

C:\Users\edu-neo\AppData\Local\Temp\ipykernel_22588\1463532809.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1['b'], s1[1]


(1.0, 1.0)

In [278]:
# slicing과 다르게 마지막을 포함한다.
s1['b':'c']

b    1.0
c    2.0
dtype: float64

In [279]:
s1[['b', 'c']]

b    1.0
c    2.0
dtype: float64

In [282]:
s1[s1 < 2]

a    0.0
b    1.0
dtype: float64

In [283]:
s1['b':'c'] = 5.

In [285]:
s1

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [287]:
f1 = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['a', 'b', 'c', 'd'])
f1

a   b   c   d
Ohio       0   1   2   3
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [288]:
# Col
f1['b']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: b, dtype: int32

In [289]:
# Col
f1[['a', 'c']]

a   c
Ohio       0   2
Colorado   4   6
Utah       8  10
New York  12  14

In [292]:
# Slicing => Row
f1['Colorado':'Utah']

a  b   c   d
Colorado  4  5   6   7
Utah      8  9  10  11

In [293]:
# 조건 => Row
f1[f1['c'] > 5]

a   b   c   d
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [295]:
f1 > 5

a      b      c      d
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [297]:
f1[f1 < 5] = 0
f1

a   b   c   d
Ohio       0   0   0   0
Colorado   0   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [299]:
# loc, iloc => 특수 색인 필드
# Numpy 와 유사하게 축의 라벨을 활용하여 DF의 Row/Col을 선택 가능.
# 축 이름을 사용할때는 loc
# 정수 index를 사용할 때는 iloc

In [302]:
f1.loc['Colorado', ['b', 'c']]

b    5
c    6
Name: Colorado, dtype: int32

In [303]:
f1.iloc[2, [3, 0, 1]]

d    11
a     8
b     9
Name: Utah, dtype: int32

In [307]:
f1.iloc[[1, 2], [3, 0, 1]]

d  a  b
Colorado   7  0  5
Utah      11  8  9

In [310]:
f1.loc[:'Utah', 'b']

Ohio        0
Colorado    5
Utah        9
Name: b, dtype: int32

In [315]:
f1.iloc[:, :3][f1['c'] > 10]

a   b   c
New York  12  13  14

In [318]:
# Series & DF 연산, 데이터 정렬

In [319]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [323]:
# 있는 값 + 없는 값 => 없는 값
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [329]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [331]:
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [330]:
# 없는 Col + 있는 Col => 전체 Col Nan / 있는 Row + 없는 Row => 전체 Row NaN
# 공통으로 존재하지 않으면 모두 NaN
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [332]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [334]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [336]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [337]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [340]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [353]:
df1 / 2 == df1.div(2)

a     b     c     d
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True

In [357]:
2 / df1 == df1.rdiv(2)

a     b     c     d
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True

In [364]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [365]:
# DataFrame <=> Series

In [372]:
# ndarray 차원이 다른 arr 연산
arr = np.arange(12.).reshape((3, 4))

arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [373]:
# 각 Row 마다 arr[0] 을 - 연산
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [378]:
df = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = df.iloc[0]
df, series

(          b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0,
 b    0.0
 d    1.0
 e    2.0
 Name: Utah, dtype: float64)

In [380]:
# DataFrame / Series 연산 => Series의 index에 DF의 컬럼을 맞추고 아래 Row 로 전파(broadcast)
df - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [382]:
s2 = pd.Series(range(3), index=list('bef'))
s2

b    0
e    1
f    2
dtype: int64

In [383]:
df + s2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [386]:
s3 = df['d']
s3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [387]:
df

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [395]:
# df - s3
df.sub(s3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [396]:
# DF 일괄 함수 적용

In [399]:
df = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [400]:
df

b         d         e
Utah   -0.410921  0.216183 -0.509322
Ohio   -0.649207  0.176166  0.359902
Texas  -1.721759  1.248739 -0.853296
Oregon  0.877372 -0.302715 -0.623136

In [401]:
# Numpy 함수 적용
np.abs(df)

b         d         e
Utah    0.410921  0.216183  0.509322
Ohio    0.649207  0.176166  0.359902
Texas   1.721759  1.248739  0.853296
Oregon  0.877372  0.302715  0.623136

In [405]:
# 컬럼별 최댓값 구하기, 최솟값
df.max(), df.min()

(b    0.877372
 d    1.248739
 e    0.359902
 dtype: float64,
 b   -1.721759
 d   -0.302715
 e   -0.853296
 dtype: float64)

In [406]:
# 컬럼별 최댓값 - 최솟값 구하기..??
df.max() - df.min()

b    2.599131
d    1.551453
e    1.213197
dtype: float64

In [409]:
def x(col):
    return col.max() - col.min()

df.apply(x)

b    2.599131
d    1.551453
e    1.213197
dtype: float64

In [411]:
# col 별 최대-최소
df.apply(lambda x: x.max() - x.min())

b    2.599131
d    1.551453
e    1.213197
dtype: float64

In [414]:
# row 별 최대-최소
df.apply(lambda x: x.max() - x.min(), axis='columns')  # 계산의 대상이 되는 것이 col 이 된다.

Utah      0.725506
Ohio      1.009108
Texas     2.970498
Oregon    1.500507
dtype: float64

In [418]:
def func(x):
    # 새로운 Series 를 반환. 아래 Series 들로 구성된 새로운 DF 를 만들 수 있다.
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

df.apply(func)

b         d         e
min -1.721759 -0.302715 -0.853296
max  0.877372  1.248739  0.359902